const checklist = [
  'Se realizó el análisis de seguridad en el trabajo.',
  'Se han consultado otros permisos y se cumple con los requerimientos de éstos.',
  'El personal cumple los requisitos de aptitud para realizar la tarea.',
  'Si va a utilizar sustancias químicas, cuenta con los controles para su manipulación.',
  'El personal cuenta con el equipo de protección definido para la tarea.',
  'Se controlaron los riesgos presentes en el sitio de trabajo.',
  'El personal cuenta con el equipo definido para acceder al sitio.',
  'Está presente una persona para activar el plan de emergencia en caso de ser necesario.',
  'El equipo para acceder al sitio y el de protección personal fueron inspeccionados.',
  'El lugar donde realizará la labor tiene instalada la línea de vida o una estructura donde el trabajador pueda asegurarse.',
  'Se verificó que la formación en alturas del personal esté acorde al trabajo a realizar.',
  'El personal que va a realizar la labor conoce el procedimiento de emergencia y rescate.',
  'El sitio donde se ejecutará el trabajo está aislado y señalizado completamente.',
  'Los andamios se encuentran completos, en sus partes y accesorios.',
  'Se han instalado mamparas o cinta para aislar y señalizar la zona y no permitir el paso de vehículos o personas.',
  'Están operando los frenos de las ruedas de los andamios.',
  'Cuentan con eslinga de seguridad con absorbente de caídas.',
  'Los canes o plataformas están asegurados y sobresalen mínimo 30 cm del andamio.',
  'Cuentan con freno de seguridad, certificado y apropiado para el tipo de línea de vida.',
  'Se ha dispuesto de los elementos necesarios para izar y descender la herramienta.',
  'Se cuenta con líneas de vida para cada uno de los operadores.',
  'Los andamios se encuentran asegurados cada tres cuerpos.',
  'Los conectores o mosquetones son de doble seguro.',
  'Las guayas de acero son del calibre definido para el tipo de andamio colgante, se encuentran en buen estado y aseguradas en forma correcta.',
  'Las cuerdas se encuentran libres de nudos.',
  'Las barandas del andamio cumplen con las especificaciones técnicas.',
  'Todos los trabajadores autorizados conocen las medidas de precaución establecidas en la evaluación de riesgos.',
  'Las escaleras cumplen con las especificaciones técnicas.',
];

const epp = [
  'Línea de vida vertical',
  'Eslinga de posicionamiento',
  'Sistemas de anclaje',
  'Arnés de cuerpo entero',
  'Guantes',
  'Línea de vida horizontal',
  'Eslinga',
  'Casco con barboquejo',
  'Señalización del área',
  'Gafas',
];

export const workAtHeightSchema = {
  title: 'Permiso de trabajo en altura',
  source: { code: 'HSE-FO-016', version: '00', date: '2022-09-30' },
  fields: [
    {
      id: 'empresa',
      type: 'select',
      label: 'Tipo de empresa',
      required: true,
      order: 1,
      section: '1. Datos básicos del permiso de trabajo en altura',
      options: ['Empresa principal', 'Empresa contratista', 'Empresa subcontratista'],
    },
    {
      id: 'ciudad',
      type: 'select',
      label: 'Ciudad',
      required: true,
      order: 2,
      section: '1. Datos básicos del permiso de trabajo en altura',
      options: ['Bogotá D.C.', 'Medellín', 'Cali', 'Barranquilla', 'Otra sede autorizada'],
    },
    {
      id: 'lugar_trabajo',
      type: 'select',
      label: 'Lugar de trabajo',
      required: true,
      order: 3,
      section: '1. Datos básicos del permiso de trabajo en altura',
      options: [
        'Instalaciones propias',
        'Instalaciones del cliente',
        'Obra en ejecución',
        'Espacio exterior controlado',
      ],
    },
    {
      id: 'area_proceso',
      type: 'select',
      label: 'Área / proceso',
      required: true,
      order: 4,
      section: '1. Datos básicos del permiso de trabajo en altura',
      options: ['Mantenimiento', 'Operaciones', 'Construcción', 'Logística', 'Servicios generales'],
    },
    {
      id: 'ubicacion_trabajo',
      type: 'multi_select',
      label: 'Ubicación donde se realiza el trabajo',
      required: true,
      order: 5,
      section: '1. Datos básicos del permiso de trabajo en altura',
      options: ['Cubierta o techo', 'Andamio', 'Escalera', 'Plataforma elevadora', 'Estructura', 'Fachada'],
    },
    {
      id: 'vigencia_permiso',
      type: 'select',
      label: 'Vigencia del permiso',
      required: true,
      order: 6,
      section: '1. Datos básicos del permiso de trabajo en altura',
      options: ['Jornada actual', 'Turno diurno', 'Turno nocturno'],
    },
    {
      id: 'fecha_trabajo',
      type: 'select',
      label: 'Fecha de realización del trabajo',
      required: true,
      order: 7,
      section: '1. Datos básicos del permiso de trabajo en altura',
      options: ['Hoy', 'Próximo turno programado'],
    },
    {
      id: 'hora_inicio',
      type: 'select',
      label: 'Hora de inicio',
      required: true,
      order: 8,
      section: '1. Datos básicos del permiso de trabajo en altura',
      options: ['06:00', '07:00', '08:00', '12:00', '14:00', '18:00'],
    },
    {
      id: 'hora_finalizacion',
      type: 'select',
      label: 'Hora de finalización',
      required: true,
      order: 9,
      section: '1. Datos básicos del permiso de trabajo en altura',
      options: ['10:00', '12:00', '14:00', '16:00', '18:00', '22:00'],
    },
    {
      id: 'certificado_alturas',
      type: 'select',
      label: 'Certificado para trabajo en alturas',
      required: true,
      order: 10,
      section: '1. Datos básicos del permiso de trabajo en altura',
      options: ['Vigente y verificado', 'Próximo a vencer', 'No vigente'],
    },
    {
      id: 'cargo_ejecutor',
      type: 'select',
      label: 'Cargo',
      required: true,
      order: 11,
      section: '1. Datos básicos del permiso de trabajo en altura',
      options: ['Trabajador autorizado', 'Coordinador de trabajo en alturas', 'Ayudante de seguridad', 'Rescatista'],
    },
    {
      id: 'seguridad_social_verificada',
      type: 'yes_no',
      label: 'Verificación de la seguridad social',
      required: true,
      order: 12,
      section: '1. Datos básicos del permiso de trabajo en altura',
    },
    {
      id: 'tipos_trabajo_altura',
      type: 'multi_select',
      label: 'Tipos de trabajos en alturas a realizar',
      required: true,
      order: 13,
      section: '2. Descripción del trabajo a realizar',
      options: [
        'Ascenso o descenso',
        'Trabajo en cubierta',
        'Trabajo en andamio',
        'Trabajo en escalera',
        'Trabajo en plataforma',
      ],
    },
    {
      id: 'herramientas',
      type: 'multi_select',
      label: 'Herramientas a utilizar',
      required: true,
      order: 14,
      section: '2. Descripción del trabajo a realizar',
      options: ['Herramienta manual', 'Herramienta eléctrica', 'Equipo de medición', 'Equipo de izaje'],
    },
    {
      id: 'altura_metros',
      type: 'select',
      label: 'Altura aproximada a la cual se va a desarrollar la actividad',
      required: true,
      order: 15,
      section: '2. Descripción del trabajo a realizar',
      options: ['Menos de 1,5 m', 'Entre 1,5 y 3 m', 'Entre 3 y 6 m', 'Más de 6 m'],
    },
    {
      id: 'peligros',
      type: 'multi_select',
      label: 'Peligros identificados',
      required: true,
      order: 16,
      section: '3. Identificación de peligros y controles',
      options: [
        'Caída a distinto nivel',
        'Caída de objetos',
        'Energía eléctrica',
        'Condiciones climáticas',
        'Superficie resbalosa',
      ],
    },
    {
      id: 'controles',
      type: 'multi_select',
      label: 'Controles ejecutados',
      required: true,
      order: 17,
      section: '3. Identificación de peligros y controles',
      options: [
        'Delimitación del área',
        'Inspección de equipos',
        'Verificación de anclajes',
        'Uso de EPP',
        'Acompañamiento del coordinador',
      ],
    },
    {
      id: 'sistemas_acceso',
      type: 'multi_select',
      label: 'Sistemas de acceso a utilizar',
      required: true,
      order: 18,
      section: '4. Medidas de prevención y protección',
      options: ['Andamio', 'Escalera', 'Elevador de personal o grúa con canasta'],
    },
    {
      id: 'otras_tar_involucradas',
      type: 'yes_no',
      label: '¿Se involucran otras tareas de alto riesgo?',
      required: true,
      order: 19,
      section: '4. Medidas de prevención y protección',
    },
    {
      id: 'otras_tar',
      type: 'multi_select',
      label: 'Otras tareas de alto riesgo involucradas',
      required: false,
      order: 20,
      section: '4. Medidas de prevención y protección',
      options: ['Espacios confinados', 'Trabajo en caliente', 'Energías peligrosas', 'Otras'],
    },
    {
      id: 'otras_tar_detalle',
      type: 'select',
      label: 'Control adicional para otras tareas de alto riesgo',
      required: false,
      order: 21,
      section: '4. Medidas de prevención y protección',
      options: ['No aplica', 'Aislamiento adicional', 'Permiso específico complementario', 'Supervisión adicional'],
    },
    {
      id: 'procedimiento',
      type: 'select',
      label: 'Procedimiento de la actividad a desarrollar',
      required: true,
      order: 22,
      section: '4. Medidas de prevención y protección',
      options: ['Inspección', 'Mantenimiento', 'Instalación', 'Limpieza', 'Montaje o desmontaje'],
    },
    ...epp.map((label, index) => ({
      id: `epp_${String(index + 1).padStart(2, '0')}`,
      type: 'yes_no',
      label,
      required: true,
      order: 230 + index,
      section: '4. Medidas de prevención y protección',
    })),
    {
      id: 'epp_otros',
      type: 'select',
      label: 'Otros elementos de protección personal o sistemas de protección contra caídas',
      required: false,
      order: 240,
      section: '4. Medidas de prevención y protección',
      options: ['No aplica', 'Protección auditiva', 'Respirador', 'Protección facial'],
    },
    ...checklist.map((label, index) => ({
      id: `verificacion_${String(index + 1).padStart(2, '0')}`,
      type: 'select',
      label,
      required: true,
      order: 100 + index,
      options: ['SI', 'NO', 'N/A'],
      section: '5. Lista de verificación de seguridad',
    })),
    {
      id: 'autorizador_nombre_documento',
      type: 'select',
      label: 'Nombre y cédula de la persona que autoriza el trabajo',
      required: true,
      order: 200,
      section: '6. Responsables y autorizaciones',
      options: ['Coordinador SST asignado', 'Supervisor de área asignado', 'Responsable HSE asignado'],
    },
    {
      id: 'responsable_emergencia',
      type: 'select',
      label: 'Nombre y cédula de la persona responsable de activar el plan de emergencia',
      required: true,
      order: 201,
      section: '6. Responsables y autorizaciones',
      options: ['Brigadista asignado', 'Coordinador SST asignado', 'Supervisor de área asignado'],
    },
    {
      id: 'coordinador_alturas',
      type: 'select',
      label: 'Nombre y cédula de la persona que autoriza (Coordinador de trabajo en altura)',
      required: true,
      order: 202,
      section: '6. Responsables y autorizaciones',
      options: ['Coordinador de alturas asignado', 'Supervisor de área asignado', 'Responsable HSE asignado'],
    },
  ],
};
